### ISSUE TITLE
Microsoft.Azure.WebJobs.Script: WorkerConfig for runtime: dotnet-isolated not found.

### ISSUE THREAD

**Issue by elliotchaim** [Azure/azure-functions-core-tools#2956]
I'm trying to deploy an Azure Functions app (net6.0 isolated functions v4) to Azure (Linux P1v2 app service plan). the app is containerized with `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0` base image. i'm deploying and see logs in deployment center showing that the image was downloaded and container started. but no functions have been found and i get this error notification in the azure portal:

```
Microsoft.Azure.WebJobs.Script: WorkerConfig for runtime: dotnet-isolated not found.
```

i can't find any docs whatsover around setting up deployments to azure for functions v4 aside from deploying straight from vs code using the extension (not what i want to do). im trying to setup deployment of a production application from CI/CD using terraform

thanks

**Comment by elliotchaim** [comment]
I have some new information for this which you may find useful.

* Adding the app setting `WEBSITES_ENABLE_APP_SERVICE_STORAGE=false` on our Azure app service resolved the WorkerConfig runtime error.
* Updated worker nugets to the following versions
```
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
```

Now when running the container I can see the following output.

```
info: Host.Function.Console[0]
      It was not possible to find any compatible framework version
info: Host.Function.Console[0]
      The framework 'Microsoft.AspNetCore.App', version '6.0.0' (x64) was not found.
info: Host.Function.Console[0]
        - No frameworks were found.
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      You can resolve the problem by installing the specified framework and/or SDK.
info: Host.Function.Console[0]
info: Host.Function.Console[0]
      The specified framework can be found at:
info: Host.Function.Console[0]
        - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=debian.11-x64
```

After this output, the host starts successfully. BUT when a function is triggered (in my case a Timer triggered function) I can see the following error:

```
fail: Function.ProcessTransactionFiles[3]

      Executed 'Functions.ProcessTransactionFiles' (Failed, Id=068bc539-f63c-4f3a-9d1a-fac8c03c8c87, Duration=44738ms)

      Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessTransactionFiles

       ---> System.InvalidOperationException: Did not find any initialized language workers

         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27

         at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 389

         at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 95

         at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82

         at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20

         at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52

         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 596

         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 542

         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 320

         --- End of inner exception stack trace ---

         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 367

         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108
```

**Comment by ChrisKlug** [comment]
I've got the same issue. However, it actually used to work for us. But after a redeploy, we started getting this issue.

Our function isn't containerized though. So it is not only for containerized function. However, we are using .NET 6.0, dotnet-isolated and extension version 4, so it sounds a LOT like the same issue.

I've tried re-deploying the whole app service, but it just comes back with the same issue. Any information would be appreciated!

**Comment by drmathias** [comment]
I'm deploying with Bicep. Was working fine until I deployed it again this morning, now getting this error.

**Comment by ChrisKlug** [comment]
So am I. It has worked fine previously, but stopped working for our deployments today. However, adding the above mentioned `runtimeStack` setting seems to have solved to problem for us

**Comment by drmathias** [comment]
Unfortunately didn't solve the issue for me.

Worth mentioning that I'm deploying to a Windows app service, so this isn't exclusive to app service for linux.

**Comment by ChrisKlug** [comment]
Apparently it didn't solve it for me either. Every time I re-deploy the bicep files, the function dies. However, re-deploying the code seems to reset it. Not a really good solution though...
